import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    //justifyContent: 'center',
    //alignItems: 'left',
 //   alignItems: 'flex-stretch',
    alignItems: 'stretch',
    paddingHorizontal: 24,
    paddingTop: 24
  },
  header:{
    flexDirection: 'row',
    alignItems: 'center',
    gap:18,
   // marginRight: 8,
   //// marginBottom:16,
   // flexShrink:0,
  },
  headerRight:{
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  searchContainer:{
    flex: 1,
    marginRight: 8,
 //   minWidth: 80,
    flexDirection: 'row',
    alignItems : 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 10,
   // paddingVertical: 7,
 //   gap: 10,
  //  overflow: 'hidden',
    height: 36,
  },
  searchInput: {
    flex: 1,
   // flexDirection: 'column',
    fontSize: 14,
    color: '#111',
    padding:15,
    //paddingHorizontal: 3,
    // paddingVertical: 1,
    outlineStyle: 'none',
  },
  subtitle: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 24,
  },
  button: {
    height: 36,
   // alignSelf: 'stretch',
   // aspectRatio: undefined,
    borderRadius: 10,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
