import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2e4e4',
  },
  topTrim: {
    position: 'absolute',
    top: 0,
    left: '-1%',
    width: '102%',
    height: 154,
    zIndex: 2,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  foreground: {
    flex: 1,
    paddingHorizontal: 18,
  },
  headerOverlay: {
    position: 'absolute',
    left: 18,
    right: 18,
    zIndex: 5,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  titlePill: {
    backgroundColor: '#e2e2e2',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#d0cccc',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  headerSideSpacer: {
    width: 38,
    height: 38,
  },
  title: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 24,
    color: '#5c3d3d',
  },
  searchContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f2e9e9',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 0,
    height: 42,
    borderWidth: 1,
    borderColor: '#a99595',
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Gaegu-Bold',
    fontSize: 20,
    color: '#5c3d3d',
    paddingHorizontal: 8,
    paddingVertical: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
    outlineStyle: 'none',
  },
  searchArea: {
    width: '52%',
    minWidth: 150,
    maxWidth: 240,
    marginLeft: 12,
    zIndex: 20,
  },
  subtitle: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 20,
    color: '#7a6161',
    marginBottom: 16,
    marginTop: 4,
  },
  logoutIconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#f66767',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homebuttons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#e9dadc',
    borderWidth: 1,
    borderColor: '#b9a1a1',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  notifButtonWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  notifBadgeDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 5,
    backgroundColor: '#e84855',
    zIndex: 1,
  },
  quickActionsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  leftActionsColumn: {
    flex: 1,
    alignItems: 'flex-start',
    gap: 8,
    paddingRight: 12,
  },
  notificationsText: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 18,
    color: '#5f4b4b',
  },
  streaksText: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 18,
    color: '#5f4b4b',
  },
  projectsText: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 18,
    color: '#5f4b4b',
  },
  welcome: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 22,
    color: '#5c3d3d',
    marginBottom: 2,
  },
  welcomeRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    paddingTop: 24,
    paddingBottom: 12,
    paddingHorizontal: 12,
    marginBottom: 4,
  },
  welcomeUser: {
    flex: 1,
    flexShrink: 1,
    fontFamily: 'Gaegu-Bold',
    fontSize: 22,
    color: '#5c3d3d',
  },
  catColumn: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    marginTop: -8,
  },
  feedStateText: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 18,
    color: '#6f5a5a',
    textAlign: 'center',
    paddingVertical: 12,
  },
  refreshSpinnerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -16,
    marginBottom: 10,
  },
  refreshSpinnerImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  floatingPostButton: {
    position: 'absolute',
    right: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 24,
    height: 52,
    borderWidth: 1,
    borderColor: '#e3d3d3',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 4,
    zIndex: 30,
  },
  floatingPostButtonText: {
    fontFamily: 'Gaegu-Bold',
    fontSize: 24,
    color: '#5c3d3d',
    lineHeight: 26,
  },
});
