import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2e4e4',
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  foreground: {
    flex: 1,
    paddingHorizontal: 24,
  },
  header:{
    flexDirection: 'row',
    alignItems: 'center',
    gap:18,
   // marginRight: 8,
   //// marginBottom:16,
   // flexShrink:0,
  },
  headerRight:{
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  searchContainer:{
    flex: 1,
    marginRight: 8,
 //   minWidth: 80,
    flexDirection: 'row',
    alignItems : 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 0,
   // paddingVertical: 7,
 //   gap: 10,
  //  overflow: 'hidden',
    height: 40,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#111111',
    paddingHorizontal: 8,
    paddingVertical: 0,
    //paddingHorizontal: 3,
    // paddingVertical: 1,
    includeFontPadding: false,
    textAlignVertical: 'center',
    outlineStyle: 'none',
  },
  subtitle: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 24,
  },
  button: {
    height: 36,
   // alignSelf: 'stretch',
   // aspectRatio: undefined,
    borderRadius: 10,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  logoutIconButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homebuttons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8, // space between icon and text
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  quickActionsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  leftActionsColumn: {
    flex: 1,
    alignItems: 'flex-start',
    gap: 8,
    paddingRight: 12,
  },
  catColumn: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  }
});
